// Language: rest

### GET ALL Users
GET http://localhost:3000/school/students HTTP/1.1


### GET User by ID
GET http://localhost:3000/school/get-student/67e58d2437d77a20a4b016f1 HTTP/1.1


### ADD User
POST http://localhost:3000/school/add-student HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Carter",
  "email": "john.carter@mail.com",
  "yearOfAdmission": "2020",
  "courseOfStudy": "Computer Science"
}


### UPDATE User
PUT http://localhost:3000/school/update-student/67e58d2437d77a20a4b016f1 HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Rambo",
  "courseOfStudy": "Medicine & Surgery",
  "yearOfAdmission": "2019"
}


### DELETE User
DELETE http://localhost:3000/school/delete-student/67e58e6737d77a20a4b016f4 HTTP/1.1
 

### GET ALL Instructors
GET http://localhost:3000/school/instructors HTTP/1.1


### GET Instructor by ID
GET http://localhost:3000/school/get-instructor/67e58d2437d77a20a4b016f1 HTTP/1.1


### ADD Instructor
POST http://localhost:3000/school/add-instructor HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Carter",
  "email": "john.carter@mail.com",
  "coursesTaught": ["physics","maths"],
  "yearOfEmployment": "2015"
}


### UPDATE Instructor
PUT http://localhost:3000/school/update-instructor/67e58d2437d77a20a4b016f1 HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Rambo",
  "coursesTaught": ["physics","chemistry"],
  "yearOfEmployment": "2019"
}


### DELETE Instructor
DELETE http://localhost:3000/school/delete-instructor/67e58e6737d77a20a4b016f4 HTTP/1.1
 